//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OpenGLSetting.rc
//
#define IDAPPLY                         20000
#define IDC_DEFAULT                     20001
#define IDD_DIALOG_SETTING_LIGHT        20002
#define IDD_DIALOG_SETTING_MATERIAL     20003
#define IDC_SLIDER_AMBIENT_RED          20004
#define IDC_SLIDER_AMBIENT_GREEN        20005
#define IDC_SLIDER_AMBIENT_BLUE         20006
#define IDC_SLIDER_AMBIENT_ALFA         20007
#define IDC_SLIDER_DIFFUSE_RED          20008
#define IDC_SLIDER_DIFFUSE_GREEN        20009
#define IDC_SLIDER_DIFFUSE_BLUE         20010
#define IDC_SLIDER_DIFFUSE_ALFA         20011
#define IDC_SLIDER_SPECULAR_RED         20012
#define IDC_SLIDER_SPECULAR_GREEN       20013
#define IDC_SLIDER_SPECULAR_BLUE        20014
#define IDC_SLIDER_SPECULAR_ALFA        20015
#define IDC_SLIDER_EMITTED_RED          20016
#define IDC_SLIDER_EMITTED_GREEN        20017
#define IDC_SLIDER_EMITTED_BLUE         20018
#define IDC_SLIDER_EMITTED_ALFA         20019
#define IDC_SLIDER_SHININESS            20020
#define IDC_EDIT_POSITION_X             20021
#define IDC_EDIT_POSITION_Y             20022
#define IDC_EDIT_POSITION_Z             20023
#define IDC_CHECK_POSITION_W            20024
#define IDC_EDIT_SPOT_DIRECTION_X       20025
#define IDC_EDIT_SPOT_DIRECTION_Y       20026
#define IDC_EDIT_SPOT_DIRECTION_Z       20027
#define IDC_EDIT_SPOT_EXPONENT          20028
#define IDC_EDIT_SPOT_CUTOFF            20029
#define IDC_EDIT_ATTENUATION_CONSTANT   20030
#define IDC_EDIT_ATTENUATION_LINEAR     20031
#define IDC_EDIT_ATTENUATION_QUADRATIC  20032
#define IDC_STATIC_CURRENT              20033
#define IDC_CHECK_USE_GL_BEND           20034
#define IDC_CHECK_HIDE_OBJECT           20035
#define IDC_LIST_OBJECT                 20036
#define IDD_DIALOG_SETTING_MATERIAL_MULTIOBJECT 20037

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	1000
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		1000
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
